web/chatme/forms.py
from flask_wtf import FlaskForm
from flask_babel import _
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class MessageForm(FlaskForm):
    message = TextAreaField(_('Message'), validators=[DataRequired(), Length(min=0, max=140)])
    submit = SubmitField('<i data-acorn-icon="navigate-diagonal" class="icon" data-acorn-size="18"></i>')

web/chatme/routes.py
import datetime
from email.mime.text import MIMEText
import smtplib, os
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy import distinct, func 

from sqlalchemy.future import select
from sqlalchemy.sql import or_ , and_
from web.utils.chat_list import chat_list

from web.extensions import socketio
from web.chatme.forms import MessageForm
from web.models import db, User, Message

chat = Blueprint('chat', __name__)

#@chat.route('/chat', methods=['GET', 'POST'])
@chat.route('/chat/<string:usr>', methods=['GET', 'POST'])
@login_required
def chst(usr):
    usr = User.query.filter_by(username=usr).first_or_404()

    our_chat = Message.query.filter(
    and_(Message.recipient == current_user, Message.author == usr) | \
        (and_(Message.recipient == usr, Message.author == current_user) ) )
    
    form = MessageForm()
    flash(f'Your Message({form.errors}).', 'danger') if not form.validate_on_submit() else ''
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=usr, body=form.message.data)
        usr.notify('count_unread', usr.count_unread())
        db.session.add(msg)
        db.session.commit()
        flash(f'Your Message Has Been Sent.', 'success')

    return render_template('chatme/chat.html', user=usr, form=form, chat = [c for c in our_chat])

"""db.session.query(
    UserModel.city
).distinct().all()
"""
@chat.route('/chat')
@login_required
def list():
    current_user.last_message_read_time = func.now()
    current_user.notify('count_unread', 0)
    db.session.commit()

    #conversation = Message.query.filter(or_(Message.recipient == current_user, Message.author == current_user)).order_by(Message.created.desc()).distinct()
    #conversation = Message.query.filter( or_(current_user != Message.recipient, current_user != Message.author), and_(Message.author == current_user, Message.recipient == current_user)).distinct()
    conversation = User.query.filter(or_(Message.recipient == current_user, Message.author == current_user)).order_by(Message.created.desc()).distinct() 
    query = select(User.id, User.username, User.image).where(or_(Message.recipient == current_user, Message.author == current_user)).distinct()
    context = {
        'chats': conversation, #'chatsx': [ m for m in conversation]
        'chat':  [ m for m in conversation ],
        'query': query
    }
    print(conversation)
        
    return render_template('chatme/chatlist.html', **context)

#send message route
@chat.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user, body=form.message.data)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.add(msg)
        db.session.commit()
        flash( ('Your message has been sent.'))
        return redirect(url_for('main.user', username=recipient))
    return render_template('chatme/send_message.html', form=form, recipient=recipient)


#view message route
@chat.route('/email')
def email():
    try:
        gmail = smtplib.SMTP('smtp.gmail.com', 587)
        gmail.ehlo()
        gmail.starttls()
        gmail.login('jameschristo962@gmail.com', os.environ.get('EMAIL_PASSWORD') )
        #gmail.login(FROM_EMAIL,PASSWORD)
        return 'success 1'
    except:
        print("Couldn't setup email!!")
        msg=MIMEText('message')
        msg['Subject']='subject'
        msg['To']=','.join('jameschristo962@gmail.com')
        msg['From']='jameschristo962@gmail.com'
        return 'failure 1'
    try:
        gmail.send_message(msg)
        return 'success 2'
    except:
        print("COULDN'T SEND EMAIL")
        return 'failure 2'

#view message route
@chat.route('/messages')
@login_required
def messages():
    #current_user.last_message_read_time = datetime.utcnow() 
    current_user.last_message_read_time = func.now()
    current_user.notify('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    messages = current_user.messages_received.order_by(
        Message.created.desc()).paginate( page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    next_url = url_for('chat.messages', page=messages.next_num) if messages.has_next else None
    prev_url = url_for('chat.messages', page=messages.prev_num) if messages.has_prev else None
    return render_template('chatme/messages.html', messages=messages.items, next_url=next_url, prev_url=prev_url)


@socketio.on('/echo')
def echo(ws):
    while True:
        data = ws.receive()
        ws.send(data)


@socketio.on('message')
def message(data):
    print(f'\n\n{data}\n\n')
    send(data)

web/templates/chatme/_post.html
    <table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('main.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(70) }}" />
                </a>
            </td>
            <td>
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', username=post.author.username) }}">
                            {{ post.author.username }}
                        </a>
                    </span>
                {% endset %}
                {{ _('%(username)s said %(when)s',
                    username=user_link, when=moment(post.timestamp).fromNow()) }}
                <br>
                <span id="post{{ post.id }}">{{ post.body }}</span>
                {% if post.language and post.language != g.locale %}
                <br><br>
                <span id="translation{{ post.id }}">
                    <a href="javascript:translate(
                                '#post{{ post.id }}',
                                '#translation{{ post.id }}',
                                '{{ post.language }}',
                                '{{ g.locale }}');">{{ _('Translate') }}</a>
                </span>
                {% endif %}
            </td>
        </tr>
    </table>

web/templates/chatme/chatlist.html
{% extends 'base.html' %}
{% block title %} Chats . Russian {% endblock title %}
{% block content %}

<main>
    <div class="container col-8">
        <div class="page-title-container">
            <div class="row">
                <div class="col-auto mb-2 mb-md-0">
                    <div class="sw-md-30 sw-lg-40 w-100">
                        <h1 class="mb-0 pb-0 display-4" id="title">Chatme . Developers</h1>
                    </div>
                </div>
                <div class="col-12 col-md d-flex align-items-start justify-content-md-end">
                    <button type="button" class="btn btn-icon btn-icon-only btn-outline-primary ms-1 disabled d-none"
                        id="backButton">
                        <i data-acorn-icon="arrow-left" data-acorn-icon-size="20" class="icon"></i>
                    </button>
                    <button type="button" class="btn btn-outline-primary btn-icon btn-icon-start ms-1 w-100 w-md-auto"
                        disabled="disabled">
                        <i data-acorn-icon="plus" data-acorn-icon-size="20" class="icon"></i>
                        <span>Add Contact</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="row flex flex-grow-1 overflow-hidden pb-2 h-100">

            <div class="col h-100 d-flex" id="chatView">
                <div class="flex-column h-100 w-100 d-flex" id="chatMode">
                    <div class="card h-100 mb-2 py-5" style="height:40rem !important">

                        <div class="card-body d-flex flex-column h-100 w-100 position-relative">
                            <div class="d-flex flex-row align-items-center mb-3">
                                <div class="row g-0 sh-6 align-self-start" id="contactTitle">
                                    <div class="col-auto">
                                        <div class="sh-6 sw-6 d-inline-block position-relative">
                                            <img src="{{url_for('static', filename='img/profile/'+ current_user.image)}}"
                                                class="img-fluid rounded-xl border border-2 border-foreground profile"
                                                alt="thumb">
                                            <i class="p-1 border border-1 border-foreground bg-primary position-absolute rounded-xl e-0 t-0 status"></i>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div
                                            class="card-body d-flex flex-row pt-0 pb-0 pe-0 pe-0 ps-2 h-100 align-items-center justify-content-between">
                                            <div class="d-flex flex-column">
                                                <div class="name">{{current_user.name or current_user.username or 'Russian Hackers'}}</div>
                                                <div class="text-small text-muted last">{{current_user.last_seen|time_ago}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn btn-outline-primary btn-icon btn-icon-only ms-1 ms-auto" id="callButton"
                                    data-bs-toggle="tooltip" data-bs-placement="bottom" title=""
                                    data-delay="{'show':'250', 'hide':'0'}" data-bs-original-title="Call">
                                    <i data-acorn-icon="phone" data-acorn-icon-size="20" class="icon"></i>
                                </button>
                                <button type="button" class="btn btn-outline-primary btn-icon btn-icon-only ms-1"
                                    id="videoCallButton" data-bs-toggle="tooltip" data-bs-placement="bottom" title=""
                                    data-delay="{'show':'250', 'hide':'0'}" data-bs-original-title="Video Call">
                                    <i data-acorn-icon="video" data-acorn-icon-size="20" class="icon"></i>
                                </button>
                            </div>

                            <div class="separator-light mb-3"></div>

                            <div class="h-100 mb-n2 scroll-out">
                                <div class="h-100 os-host os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-overflow os-host-overflow-y os-host-transition"
                                    id="chatContentContainer">
                                    <div class="os-resize-observer-host observed">
                                        <div class="os-resize-observer" style="left: 0px; right: auto;"></div>
                                    </div>
                                    <div class="os-size-auto-observer observed"
                                        style="height: calc(100% + 1px); float: left;">
                                        <div class="os-resize-observer"></div>
                                    </div>
                                    <div class="os-content-glue"
                                        style="margin: 0px -15px; width: 1107px; height: 204px;"></div>

                                    <div class="os-padding">
                                        <div class="os-viewport os-viewport-native-scrollbars-invisible"
                                            style="overflow-y: scroll;">
                                            <div class="os-content" style="padding: 0px 15px; height: 100%; width: 100%;">
                                               <!--  <h1>{{query}} </h1> -->
                                        {% for c in chat  %}
                                                <div class="bg-separator-light rounded-md mb-2  py-3 px-3 pe-7 position-relative text-alternate">
                                                    <a href="{{url_for('chat.chst', user = c.username)}}"
                                                        class="row  w-100 d-flex flex-row g-0 sh-5 mb-2 nav-link p-0 contact-list-item"
                                                        data-id="2">
                                                        <div class="col-auto ">
                                                            <div class="sw-5 d-inline-block position-relative">
                                                                <img src="{{url_for('static', filename='img/profile/'+ c.image)}}"
                                                                    class="img-fluid rounded-xl border border-2 border-foreground"
                                                                    alt="thumb" id="contactImage">
                                                                <i class="p-1 border border-1 border-foreground bg-primary position-absolute rounded-xl e-0 t-0 d-none"
                                                                    id="contactStatus"></i>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="card-body d-flex flex-row pt-0 pb-0 ps-3 pe-0 h-100 align-items-center justify-content-between">
                                                                <div class="d-flex flex-column">
                                                                    <div class="mb-1" id="contactName">{{c.name or c.username}} </div>
                                                                    <div class="text-small text-muted clamp-line" data-line="1" id="contactLastSeen" style="overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 1;">
                                                                       {{c.messages_sent or c.messages_received.body}}..... {{c.created|time_ago}}</div>
                                                                </div>
                                                                <div class="d-flex">
                                                                    <div class="badge bg-primary" id="contactUnread">2 {{c.body|length()}} </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            {% endfor %} 

                                        {% if not chat %}

                                        <div class="col-12 col-lg p-0 h-100">
                                            <div class="card-body h-100">
                                                <div class="row gx-2 d-flex h-100 align-items-lg-center">
                                                    <div class="col-lg-12 mb-2 mb-lg-1">
                                                        <a href="#" class="stretched-link body-link">
                                                        <h1 class="mb-0 pb-0 display-10 text-primary" id="title"> 0 Chat Available</h1>
                                                        <b class="text-primary"> Your Conversations Will Be Listed Here When You Send Or Receive Messages </b>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {% endif %}

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock content %}

web/templates/chatme/messages.html
{% extends 'base.html' %}
{% block title %} Chats . Russian {% endblock title %}
{% block content %}

<main>
    <div class="container col-8">
        <div class="page-title-container">
            <div class="row">
                <div class="col-auto mb-2 mb-md-0">
                    <div class="sw-md-30 sw-lg-40 w-100">
                        <h1 class="mb-0 pb-0 display-4" id="title">Chatme . Developers</h1>
                    </div>
                </div>
                <div class="col-12 col-md d-flex align-items-start justify-content-md-end">
                    <button type="button" class="btn btn-icon btn-icon-only btn-outline-primary ms-1 disabled d-none"
                        id="backButton">
                        <i data-acorn-icon="arrow-left" data-acorn-icon-size="20" class="icon"></i>
                    </button>
                    <button type="button" class="btn btn-outline-primary btn-icon btn-icon-start ms-1 w-100 w-md-auto"
                        disabled="disabled">
                        <i data-acorn-icon="plus" data-acorn-icon-size="20" class="icon"></i>
                        <span>Add Contact</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="row flex flex-grow-1 overflow-hidden pb-2 h-100">

            <div class="col h-100 d-flex" id="chatView">
                <div class="flex-column h-100 w-100 d-flex" id="chatMode">
                    <div class="card h-100 mb-2 py-5" style="height:40rem !important">

                        <div class="card-body d-flex flex-column h-100 w-100 position-relative">
                            <div class="d-flex flex-row align-items-center mb-3">
                                <div class="row g-0 sh-6 align-self-start" id="contactTitle">
                                    <div class="col-auto">
                                        <div class="sh-6 sw-6 d-inline-block position-relative">
                                            <img src="{{url_for('static', filename='img/profile/'+ current_user.photo)}}"
                                                class="img-fluid rounded-xl border border-2 border-foreground profile"
                                                alt="thumb">
                                            <i class="p-1 border border-1 border-foreground bg-primary position-absolute rounded-xl e-0 t-0 status"></i>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div
                                            class="card-body d-flex flex-row pt-0 pb-0 pe-0 pe-0 ps-2 h-100 align-items-center justify-content-between">
                                            <div class="d-flex flex-column">
                                                <div class="name">{{current_user.name or current_user.username or 'Russian Hackers'}}</div>
                                                <div class="text-small text-muted last">{{current_user.last_seen|time_ago}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn btn-outline-primary btn-icon btn-icon-only ms-1 ms-auto" id="callButton"
                                    data-bs-toggle="tooltip" data-bs-placement="bottom" title=""
                                    data-delay="{'show':'250', 'hide':'0'}" data-bs-original-title="Call">
                                    <i data-acorn-icon="phone" data-acorn-icon-size="20" class="icon"></i>
                                </button>
                                <button type="button" class="btn btn-outline-primary btn-icon btn-icon-only ms-1"
                                    id="videoCallButton" data-bs-toggle="tooltip" data-bs-placement="bottom" title=""
                                    data-delay="{'show':'250', 'hide':'0'}" data-bs-original-title="Video Call">
                                    <i data-acorn-icon="video" data-acorn-icon-size="20" class="icon"></i>
                                </button>
                            </div>

                            <div class="separator-light mb-3"></div>

                            <div class="h-100 mb-n2 scroll-out">
                                <div class="h-100 os-host os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-overflow os-host-overflow-y os-host-transition"
                                    id="chatContentContainer">
                                    <div class="os-resize-observer-host observed">
                                        <div class="os-resize-observer" style="left: 0px; right: auto;"></div>
                                    </div>
                                    <div class="os-size-auto-observer observed"
                                        style="height: calc(100% + 1px); float: left;">
                                        <div class="os-resize-observer"></div>
                                    </div>
                                    <div class="os-content-glue"
                                        style="margin: 0px -15px; width: 1107px; height: 204px;"></div>

                                    <div class="os-padding">
                                        <div class="os-viewport os-viewport-native-scrollbars-invisible"
                                            style="overflow-y: scroll;">
                                            <div class="os-content"
                                                style="padding: 0px 15px; height: 100%; width: 100%;">
                                                <h1>{% set ct = current_user.messages() %} </h1><br>
                                                <h1>{{ct}} </h1><br>

                                        {% for c in current_user.messages_sent %}
                                                <div class="bg-separator-light rounded-md mb-2  py-3 px-3 pe-7 position-relative text-alternate">
                                                    <a href="{{url_for('chat.chst', user = c.username)}}"
                                                        class="row  w-100 d-flex flex-row g-0 sh-5 mb-2 nav-link p-0 contact-list-item"
                                                        data-id="2">
                                                        <div class="col-auto ">
                                                            <div class="sw-5 d-inline-block position-relative">
                                                                <img src="{{url_for('static', filename='img/profile/'+ c.recipient.photo)}}"
                                                                    class="img-fluid rounded-xl border border-2 border-foreground"
                                                                    alt="thumb" id="contactImage">
                                                                <i class="p-1 border border-1 border-foreground bg-primary position-absolute rounded-xl e-0 t-0 d-none"
                                                                    id="contactStatus"></i>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="card-body d-flex flex-row pt-0 pb-0 ps-3 pe-0 h-100 align-items-center justify-content-between">
                                                                <div class="d-flex flex-column">
                                                                    <div class="mb-1" id="contactName">{{c.name or c.username}}
                                                                    </div>
                                                                    <div class="text-small text-muted clamp-line"
                                                                        data-line="1" id="contactLastSeen"
                                                                        style="overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 1;">
                                                                       {{c.author.body or c. recipient.body}}..... {{c.created|time_ago}}</div>
                                                                </div>
                                                                <div class="d-flex">
                                                                    <div class="badge bg-primary" id="contactUnread">2 {{c.length}}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            {% endfor %}

<!--                                         {% for c in chats  %}
                                                <div class="bg-separator-light rounded-md mb-2  py-3 px-3 pe-7 position-relative text-alternate">
                                                    <a href="{{url_for('chat.chst', user = c.username)}}"
                                                        class="row  w-100 d-flex flex-row g-0 sh-5 mb-2 nav-link p-0 contact-list-item"
                                                        data-id="2">
                                                        <div class="col-auto ">
                                                            <div class="sw-5 d-inline-block position-relative">
                                                                <img src="{{url_for('static', filename='img/profile/'+ c.photo)}}"
                                                                    class="img-fluid rounded-xl border border-2 border-foreground"
                                                                    alt="thumb" id="contactImage">
                                                                <i class="p-1 border border-1 border-foreground bg-primary position-absolute rounded-xl e-0 t-0 d-none"
                                                                    id="contactStatus"></i>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="card-body d-flex flex-row pt-0 pb-0 ps-3 pe-0 h-100 align-items-center justify-content-between">
                                                                <div class="d-flex flex-column">
                                                                    <div class="mb-1" id="contactName">{{c.name or c.username}}
                                                                    </div>
                                                                    <div class="text-small text-muted clamp-line"
                                                                        data-line="1" id="contactLastSeen"
                                                                        style="overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 1;">
                                                                       {{c.body}}..... {{c.created|time_ago}}</div>
                                                                </div>
                                                                <div class="d-flex">
                                                                    <div class="badge bg-primary" id="contactUnread">2 {{c.length}}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            {% endfor %} -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card flex-column h-100 w-100 bg-gradient-single-2 d-none" id="callMode">
                    <div
                        class="bg-vertical-ornament-3 w-100 h-100 d-flex flex-column justify-content-between align-items-center">
                        <div class="card-body d-flex align-items-center flex-column flex-grow-1 w-100">
                            <div class="sw-10 mb-2 position-relative">
                                <img src="/static/img/profile/profile-1.webp"
                                    class="img-fluid rounded-xl border border-2 border-foreground profile" alt="thumb">
                            </div>
                            <div class="name text-white">Chris James</div>
                            <div class="text-white text-small time">00:00:00</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock content %}