web/chatme/routes.py
import datetime
from email.mime.text import MIMEText
import smtplib, os
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy import distinct, func 

from sqlalchemy.future import select
from sqlalchemy.sql import or_ , and_
from web.utils.chat_list import chat_list

from web.extensions import socketio
from web.chatme.forms import MessageForm
from web.models import db, User, Message

chat = Blueprint('chat', __name__)

#@chat.route('/chat', methods=['GET', 'POST'])
@chat.route('/chat/<string:usr>', methods=['GET', 'POST'])
@login_required
def chst(usr):
    usr = User.query.filter_by(username=usr).first_or_404()

    our_chat = Message.query.filter(
    and_(Message.recipient == current_user, Message.author == usr) | \
        (and_(Message.recipient == usr, Message.author == current_user) ) )
    
    form = MessageForm()
    flash(f'Your Message({form.errors}).', 'danger') if not form.validate_on_submit() else ''
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=usr, body=form.message.data)
        usr.notify('count_unread', usr.count_unread())
        db.session.add(msg)
        db.session.commit()
        flash(f'Your Message Has Been Sent.', 'success')

    return render_template('chatme/chat.html', user=usr, form=form, chat = [c for c in our_chat])

"""db.session.query(
    UserModel.city
).distinct().all()
"""
@chat.route('/chat')
@login_required
def list():
    current_user.last_message_read_time = func.now()
    current_user.notify('count_unread', 0)
    db.session.commit()

    #conversation = Message.query.filter(or_(Message.recipient == current_user, Message.author == current_user)).order_by(Message.created.desc()).distinct()
    #conversation = Message.query.filter( or_(current_user != Message.recipient, current_user != Message.author), and_(Message.author == current_user, Message.recipient == current_user)).distinct()
    conversation = User.query.filter(or_(Message.recipient == current_user, Message.author == current_user)).order_by(Message.created.desc()).distinct() 
    query = select(User.id, User.username, User.image).where(or_(Message.recipient == current_user, Message.author == current_user)).distinct()
    context = {
        'chats': conversation, #'chatsx': [ m for m in conversation]
        'chat':  [ m for m in conversation ],
        'query': query
    }
    print(conversation)
        
    return render_template('chatme/chatlist.html', **context)

#send message route
@chat.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user, body=form.message.data)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.add(msg)
        db.session.commit()
        flash( ('Your message has been sent.'))
        return redirect(url_for('main.user', username=recipient))
    return render_template('chatme/send_message.html', form=form, recipient=recipient)


#view message route
@chat.route('/email')
def email():
    try:
        gmail = smtplib.SMTP('smtp.gmail.com', 587)
        gmail.ehlo()
        gmail.starttls()
        gmail.login('jameschristo962@gmail.com', os.environ.get('EMAIL_PASSWORD') )
        #gmail.login(FROM_EMAIL,PASSWORD)
        return 'success 1'
    except:
        print("Couldn't setup email!!")
        msg=MIMEText('message')
        msg['Subject']='subject'
        msg['To']=','.join('jameschristo962@gmail.com')
        msg['From']='jameschristo962@gmail.com'
        return 'failure 1'
    try:
        gmail.send_message(msg)
        return 'success 2'
    except:
        print("COULDN'T SEND EMAIL")
        return 'failure 2'

#view message route
@chat.route('/messages')
@login_required
def messages():
    #current_user.last_message_read_time = datetime.utcnow() 
    current_user.last_message_read_time = func.now()
    current_user.notify('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    messages = current_user.messages_received.order_by(
        Message.created.desc()).paginate( page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    next_url = url_for('chat.messages', page=messages.next_num) if messages.has_next else None
    prev_url = url_for('chat.messages', page=messages.prev_num) if messages.has_prev else None
    return render_template('chatme/messages.html', messages=messages.items, next_url=next_url, prev_url=prev_url)


@socketio.on('/echo')
def echo(ws):
    while True:
        data = ws.receive()
        ws.send(data)


@socketio.on('message')
def message(data):
    print(f'\n\n{data}\n\n')
    send(data)

web/main/routes.py
from flask import jsonify, render_template, Blueprint, request, url_for
from flask_login import current_user, login_required

from web.utils.decorators import enrollment_required

from web.models import db, Brand, User, Course, Topic, Enrollment

main = Blueprint('main', __name__)

@main.route('/explore')
@main.route('/welcome/<int:offset>', methods=['post', 'get'])
@main.route('/welcome', methods=['post', 'get'])
def index(v=None):

    page = request.args.get('page', 1, type=int)

    match v:
        case 'latest':
            course = Course.query.order_by(Course.created.desc()).paginate(page=page, per_page=8)
        case 'oldest':
            course = Course.query.order_by(Course.created.asc()).paginate(page=page, per_page=8)
        case 'asc':
            course = Course.query.order_by(Course.title.asc()).paginate(page=page, per_page=8)
        case 'desc':
            course = Course.query.order_by(Course.title.desc()).paginate(page=page, per_page=8)
        case 'cat':
            cat = v.cat
            course = Course.query.filter(Course.cat.in_([c for c in cat]) ).all()
        case 'time':
            time = v.time
            course = Course.query.filter(Course.duration.in_([ t for t in time]) ).all()
        case 'price':
            min = v.min
            max = v.max
            course = Course.query.filter(Course.price >= min).filter(Course.price <= max) or \
                Course.query.filter(Course.price.in_(range(min, max)) ).all()
        case 'kword':
            kword = v.kword
            course = Course.query.msearch(kword, fields=['title','desc'] , limit=8)
        case 'rate':
            rate = v.rate
            course = Course.query.filter(Course.rating >= rate).all()
        case 'more':
            course = Course.query.order_by(Course.id.asc()).offset(5).all()
        case _:
            all = Course.query.all()
            course = all[0 : 16 ]
            total = len(all)
        
    brand = Brand.query.filter_by(id=2).first()

    context = { 
        'brand': brand, 
        'course': course, 
        'total' : total,
        'time' : "duration_choice" }

    return render_template("welcome/welcome.html", **context)

@main.route("/us")
def us():
    brand = Brand.query.filter_by(id=2).first()
    support_amount = "30, 40, 50, 70, 80, 90, 100, 200, 300, 400, 500"
    support_interval = "daily, weekly, monthly, quarterly, yearly"
    context = {
        "brand":brand, 
        "title" :'Us . Intellect',
        "support_amount" : support_amount, 
        "support_interval" : support_interval, 
    }
    return render_template('welcome/us.html', **context)

@main.route("/us-x")
def us_x():
    brand = Brand.query.filter_by(id=2).first()
    support_amount = "30, 40, 50, 70, 80, 90, 100, 200, 300, 400, 500"
    support_interval = "daily, weekly, monthly, quarterly, yearly"
    context = {
        "brand":brand, 
        "title" :'Us . Intellect',
        "support_amount" : support_amount, 
        "support_interval" : support_interval, 
    }
    return render_template('welcome/us_x.html', **context)

 
@main.route("/")
@login_required
#@confirm_email
def user():

    # Get the current user
    user = User.query.get(current_user.id)

    # Fetch all enrollments of the user
    enrollments = Enrollment.query.filter_by(user_id=user.id).all()

    # Prepare the response data
    response_data = []

    for enrollment in enrollments:
        # Get the course associated with the enrollment
        course = enrollment.course

        # Calculate the completion percentage for the course
        completion_percentage = course.calculate_completion_percentage(user)

        # Serialize the course data
        serialized_course = course.serialize(include_only=['title', 'image', 'slug'])

        # Add completion percentage to the serialized course data
        serialized_course['progress'] = completion_percentage
        serialized_course['percent_complete'] = completion_percentage

        # Append the serialized course to the response data
        response_data.append(serialized_course)

    # Return the response as JSON
    progress_data = response_data
    #print(progress_data)
    context = {
        'progress_data': progress_data
    }

    return render_template('index.html', **context )

#-> Preview Here
@main.route('/prev_/<string:slug>')
def prev_(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    course.views += 1
    db.session.commit()

    topiq = Topic.query.filter(Topic.course_id == course.id).first()

    #return f'{course.__dict__}'

    context = {
        'course': course,
        'topiq': topiq.title if topiq else '0-topic',
        #'data': course.__dict__  # Convert Course object to a dictionary
        'data': test_course.course_data  
    }
    #print(context['data'])
    return render_template('courses/prev.html', **context)

@main.route('/learn_/<string:slug>')
def learn_(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    _chapt = [c for c in course.lesson]
    _topiq = [ t for t in course.topic]
    context = {
        '_chapt': _chapt, '_topic':_topiq,
        'data': course,
    }

    return render_template("courses/learn3.html", **context)

@main.route("/blog")
def blog():
    return render_template('blog.html')

@main.route('/school')
@login_required
#@confirm_email
def school():
    return render_template("school.html")

#quiz
@main.route('/quiz')
@login_required
#@confirm_email
def quiz():
    return render_template("quiz/quiz.html")
    
@main.route('/qdetail', defaults={'one':'one'})
@main.route('/qdetail/<string:one>', defaults={'one':'one'})
@login_required
#@confirm_email
def qdetails(one):
    return render_template("quiz/qdetail.html")

@main.route('/qresult')
@login_required
#@confirm_email
def qresult():
    return render_template("quiz/qresult.html")

#path
@main.route('/paths')
@login_required
#@confirm_email
def path():
    return render_template("path/path.html")

@main.route('/path', defaults={'one':'one'})
@main.route('/path-of/<string:one>', defaults={'one':'one'})
@login_required
#@confirm_email
def path_of(one):
    return render_template("path/path-of.html")


#instructors
@main.route('/tutors')
@login_required
#@confirm_email
def tutor_list():
    return render_template("instructor/tutors.html", tutors = 't')

@main.route('/tutor', defaults={'t':'t'})
@main.route('/tutor/<string:t>', defaults={'t':'t'})
@login_required
#@confirm_email
def tut(t):
    return render_template("instructor/tutor.html", tutor = tutor.info )

@main.route('/play')
@login_required
#@confirm_email
def player():
    return render_template("misc/play.html")

@main.route('/materi')
@login_required
#@confirm_email
def materi():
    return render_template("misc/material.html")

@main.route('/syllabus')
@login_required
#@confirm_email
def syllabus():
    return render_template("misc/syllabus.html")

@main.route('/../json/search.json')
@main.route('/json/search.json')
def search():
    r = [
    {
        "title": "settings",
        "url": f"/{current_user.username}/update" if current_user.is_authenticated else url_for('auth.signin')
    },
    {
        "title": "dashboards > elearning",
        "url": "/"
    },
    {
        "title": "dashboards > School",
        "url": "/school"
    },
    ]
  
    c = Course.query.all() 
    return jsonify([ { 'label': c.title, 'url': url_for('main.prev', slug=str(c.slug) ) } for c in c] ) 

""" ========================================================================== """

# Actual learning interface
#-> Preview Here
@main.route('/prev/<string:slug>')
def prev(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    course.views += 1
    db.session.commit()

    return render_template('xcourse/prev.html')

@main.route('/learn/<string:slug>')
@login_required
@enrollment_required
def learn(slug):
    return render_template("xcourse/learn.html")

# Course insertion interface
@main.route('/x-insert')
def x_insert():
    return render_template("xcourse/x_insert.html")

# Course update interface
@main.route('/x-update')
def x_update():
    return render_template("xcourse/x_update.html")

# Lesson insertion interface
@main.route('/x-insert/lesson')
def x_insert_lesson():
    return render_template("xcourse/x_insert_lesson.html")

# Lesson update interface
@main.route('/x-update/lesson')
def x_update_lesson():
    return render_template("xcourse/x_update_lesson.html")

# Topic insertion interface
@main.route('/x-insert/topic')
def x_insert_topic():
    return render_template("xcourse/x_insert_topic.html")

# Topic update interface
@main.route('/x-update/topic')
def x_update_topic():
    return render_template("xcourse/x_update_topic.html")

web/templates/incs/alerts.html
  
 
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, msg in messages %} 
      <div class="alert alert-{{ category }} alert-dismissible fade show " role="alert">
        {{ msg }} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %} 

web/templates/incs/bottom.html
<script src="{{ url_for('static', filename='js/vendor/jquery-3.5.1.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/vendor/bootstrap.bundle.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/vendor/OverlayScrollbars.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/vendor/autoComplete.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/vendor/clamp.min.js')}}"></script>
<script src="{{ url_for('static', filename='icon/acorn-icons.js')}}"></script>
<script src="{{ url_for('static', filename='icon/acorn-icons-interface.js')}}"></script>
<script src="{{ url_for('static', filename='icon/acorn-icons-learning.js')}}"></script>

<script src="{{ url_for('static', filename='js/base/helpers.js')}}"></script>
<script src="{{ url_for('static', filename='js/base/globals.js')}}"></script>
<script src="{{ url_for('static', filename='js/base/nav.js')}}"></script>
<script src="{{ url_for('static', filename='js/base/search.js')}}"></script>
<script src="{{ url_for('static', filename='js/base/settings.js')}}"></script>

<script src="{{ url_for('static', filename='js/common.js')}}"></script>
<script src="{{ url_for('static', filename='js/scripts.js')}}"></script>

{# <!--<script src="{{ url_for('static', filename='js/pages/explore.loadmore.js')}}"></script><!-- mine --> #}

<script>$('#cyear').html(new Date().getFullYear());//copy-right-current-year</script>

web/templates/incs/bottom_js.html
<script src="./static/js/vendor/jquery-3.5.1.min.js"></script>
<script src="./static/js/vendor/bootstrap.bundle.min.js"></script>
<script src="./static/js/vendor/OverlayScrollbars.min.js"></script>
<script src="./static/js/vendor/autoComplete.min.js"></script>
<script src="./static/js/vendor/clamp.min.js"></script>
<script src="./static/icon/acorn-icons.js"></script>
<script src="./static/icon/acorn-icons-interface.js"></script>
<script src="./static/icon/acorn-icons-learning.js"></script>
<script src="./static/js/vendor/glide.min.js"></script>
<script src="./static/js/vendor/Chart.bundle.min.js"></script>
<script src="./static/js/vendor/jquery.barrating.min.js"></script>
<script src="./static/js/base/helpers.js"></script>
<script src="./static/js/base/globals.js"></script>
<script src="./static/js/base/nav.js"></script>
<script src="./static/js/base/search.js"></script>
<script src="./static/js/base/settings.js"></script>
<script src="./static/js/cs/glide.custom.js"></script>
<script src="./static/js/cs/charts.extend.js"></script>
<script src="./static/js/pages/dashboard.elearning.js"></script>
<script src="./static/js/common.js"></script>
<script src="./static/js/scripts.js"></script>


{#
    <script src="{{url_for('static', filename='js/vendor/jquery-3.5.1.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/OverlayScrollbars.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/autoComplete.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/clamp.min.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons-interface.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons-learning.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/helpers.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/globals.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/nav.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/search.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/settings.js')}}"></script>
    <script src="{{url_for('static', filename='js/common.js')}}"></script>
    <script src="{{url_for('static', filename='js/scripts.js')}}"></script>

    <script src="{{url_for('static', filename='js/vendor/glide.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/Chart.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/jquery.barrating.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/cs/glide.custom.js')}}"></script>
    <script src="{{url_for('static', filename='js/cs/charts.extend.js')}}"></script>
    <script src="{{url_for('static', filename='js/pages/dashboard.elearning.js')}}"></script>
    #}

web/templates/incs/footer.html
<footer>
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-6">
                    <p class="mb-0 text-muted text-medium">
                        Techa . Advanced Technologies... <a id="cyear"></a>
                    </p>
                </div>
                <div class="col-sm-6 d-none d-sm-block">
                    <ul class="breadcrumb pt-0 pe-0 mb-0 float-end">
                        <li class="breadcrumb-item mb-0 text-medium">
                            <a href="{{url_for('main.us')}}" target="_blank" class="btn-link">Intellect</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

web/templates/incs/nav_no_auth.html
<div id="nav" class="nav-container d-flex">
    <div class="nav-content d-flex">
        <div class="logo position-relative"><a href="{{url_for('main.index')}}"><div class="img"></div> </a> </div>
        <div class="language-switch-container">
            <button class="btn btn-empty language-button dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">EN</button>
            <div class="dropdown-menu">
                <a href="#" class="dropdown-item">DE</a>
                <a href="#" class="dropdown-item active">EN</a>
                <a href="#" class="dropdown-item">ES</a>
            </div>
        </div>
        <div class="user-container d-flex">
            <!----
        <a href="{{ url_for('auth.signin') }}" 
            class="d-flex user position-relative"  aria-haspopup="false" aria-expanded="false"> 
            <img class="profile" alt="profile" src="{{ url_for('static', filename='img/profile/default.webp') }}">
            <div class="name">Russiantechnologies </div>
        </a> ---->

        <a href="{{ url_for('auth.signin') if not current_user.is_authenticated else url_for('main.user') }}" 
        class="d-flex user position-relative" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
        
        <img class="profile" alt="profile" src="{{ url_for('static', 
        filename='img/profile/'+ (current_user.image | default('default.webp')) )}}">

        <div class="name"> {{ current_user.name or current_user.username or "Russiantechnologies" }} </div>
    </a>

        
            <div class="dropdown-menu dropdown-menu-end user-menu wide">
                {% if current_user.is_authenticated %}
                <div class="row mb-3 ms-0 me-0">
                    <div class="col-12 ps-1 mb-2">
                        <div class="text-extra-small text-primary">ACCOUNT ( {{ current_user.created|time_ago }} )</div>
                    </div>
                    <div class="col-6 ps-1 pe-1">
                        <ul class="list-unstyled">
                            <li>
                                <a href="{{url_for('auth.update', username=current_user.username)}}">profile</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6 pe-1 ps-1">
                        <ul class="list-unstyled">
                            <li> <a href="/pay">Billing</a>  </li>
                        </ul>
                    </div>
                </div>
                <div class="row mb-1 ms-0 me-0">
                    <div class="col-12 p-1 mb-2 pt-2">
                        <div class="text-extra-small text-primary">DEVELOPERS</div>
                    </div>
                    <div class="col-6 ps-1 pe-1">
                        <ul class="list-unstyled">
                            <li> <a href="/dev">Build</a> </li>
                            <li> <a href="">community</a>  </li>
                        </ul>
                    </div>
                    <div class="col-6 pe-1 ps-1">
                        <ul class="list-unstyled">
                            <li> <a href="/share">share</a> </li>
                            <li> <a href="">Twitter</a></li>
                        </ul>
                    </div>
                </div>
                <div class="row mb-1 ms-0 me-0">
                    <div class="col-12 p-1 mb-3 pt-3">
                        <div class="separator-light"></div>
                    </div>
                    <div class="col-6 ps-1 pe-1">
                        <ul class="list-unstyled">
                            <li>
                                <a href="/help">
                                    <i data-acorn-icon="help" class="me-2" data-acorn-size="17"></i>
                                    <span class="align-middle">Help</span>
                                </a>
                            </li>
                            <li>
                                <a href="/docs">
                                    <i data-acorn-icon="file-text" class="me-2" data-acorn-size="17"></i>
                                    <span class="align-middle">Docs</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6 pe-1 ps-1">
                        <ul class="list-unstyled">
                            <li>
                                <a href="{{url_for('auth.update', username=current_user.username)}}">
                                    <i data-acorn-icon="gear" class="me-2" data-acorn-size="17"></i>
                                    <span class="align-middle">Settings</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{url_for('auth.signout')}}">
                                    <i data-acorn-icon="logout" class="me-2" data-acorn-size="17"></i>
                                    <span class="align-middle">Logout</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                {% endif %}

            </div>
        </div>

        {% include('incs/notify.html') %}

        <div class="menu-container flex-grow-1">
            <ul id="menu" class="menu">
                {% if current_user.is_authenticated %}
                <li>
                    <a href="#dashboards">
                        <i data-acorn-icon="home-garage" class="icon" data-acorn-size="18"></i>
                        <span class="label">Dashboards</span>
                    </a>
                    <ul id="dashboards">
                        <li>
                            <a href="/">
                                <span class="label">My learning</span>
                            </a>
                        </li>
                        <li>
                            <a href="/qresult">
                                <span class="label">My-quizzes</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="/quiz">
                        <i data-acorn-icon="quiz" class="icon" data-acorn-size="18"></i>
                        <span class="label">Quizzes</span>
                    </a>
                </li>
                
                <li>
                    <a href="/materi">
                        <i data-acorn-icon="destination" class="icon" data-acorn-size="18"></i>
                        <span class="label">Materi</span>
                    </a>
                </li>
                {% endif %}

                <li>
                    <a href="{{url_for('main.index')}}">
                        <i data-acorn-icon="navigate-diagonal" class="icon" data-acorn-size="18"></i>
                        <span class="label">Courses</span>
                        <ul>
                            <li></li>
                        </ul>
                    </a>
                </li>
                <li>
                    <a href="{{url_for('main.us')}}">
                        <i data-acorn-icon="image" class="icon" data-acorn-size="18"></i>
                        <span class="label">Us</span>
                    </a>
                </li>
                <li class="isDisabled">
                    <a href="{{url_for('main.blog')}}">
                        <i data-acorn-icon="file-text" class="icon" data-acorn-size="18"></i>
                        <span class="label">Blog</span>
                    </a>
                </li>

<!--------------------------Disabled below links for now ------------------->
                {% if current_user.is_authenticated and current_user.is_admin() %}
                <li class="isDisabled">
                    <a href="#quiz2" aria-disabled="true">
                    <i data-acorn-icon="file-image" class="icon" data-acorn-size="18"></i>
                        <span class="label">Quiz</span>
                    </a>
                    <ul id="quiz2">
                        <li>
                            <a href="/quiz2" aria-disabled="true">
                                <span class="label">Quizzes</span>
                            </a>
                        </li>
                        <li>
                            <a href="/qresult2" aria-disabled="true">
                                <span class="label">My result</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="isDisabled">
                    <a href="{{url_for('chat.list')}}" aria-disabled="true">
                        <i data-acorn-icon="online-class" class="icon" data-acorn-size="18"></i>
                        <span class="label">Chatme</span>
                        <ul>
                            <li></li>
                        </ul>
                    </a>
                </li>

                <li class="isDisabled">
                    <a href="{{url_for('main.path')}}" aria-disabled="true">
                        <i data-acorn-icon="destination" class="icon" data-acorn-size="18"></i>
                        <span class="label">Paths</span>
                    </a>
                </li>
                <li class="isDisabled">
                    <a href="{{url_for('main.tutor_list')}}" aria-disabled="true">
                        <i data-acorn-icon="lecture" class="icon" data-acorn-size="18"></i>
                        <span class="label">Instructors</span>
                    </a>
                </li>
                <li class="isDisabled">
                    <a href="#misc" aria-disabled="true">
                        <i data-acorn-icon="layout-5" class="icon" data-acorn-size="18"></i>
                        <span class="label">Misc</span>
                    </a>
                    <ul id="misc" >
                        <li>
                            <a href="{{url_for('main.school')}}" aria-disabled="true">
                                <span class="label">School</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{url_for('main.player')}}" aria-disabled="true">
                                <span class="label">Play</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{url_for('main.materi')}}" aria-disabled="true">
                                <span class="label">Material</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{url_for('main.syllabus')}}" aria-disabled="true">
                                <span class="label">Syllabus</span>
                            </a>
                        </li>
                    {% endif %}

                    </ul>
                </li>
                
            </ul>
        </div>

        <div class="mobile-buttons-container">
            <a href="#" id="scrollSpyButton" class="spy-button" data-bs-toggle="dropdown">
                <i data-acorn-icon="menu-dropdown"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end" id="scrollSpyDropdown"></div>
            <a href="#" id="mobileMenuButton" class="menu-button">
                <i data-acorn-icon="menu"></i>
            </a>
        </div>
        
    </div>
    <div class="nav-shadow"></div>
</div>

<style>
.isDisabled {
  color: currentColor;
  cursor: not-allowed;
  opacity: 0.5;
  text-decoration: none;
  pointer-events: none;
}

a[aria-disabled="true"] {
  color: currentColor;
  display: inline-block;  /* For IE11/ MS Edge bug */
  pointer-events: none;
  text-decoration: none;
}
</style>
<script>
    document.body.addEventListener('click', function (event) {
  // filter out clicks on any other elements
  if (event.target.nodeName == 'A' && event.target.getAttribute('aria-disabled') == 'true') {
    event.preventDefault();
  }
});
</script>