web/main/routes.py
from flask import jsonify, render_template, Blueprint, request, url_for
from flask_login import current_user, login_required

from web.utils.decorators import enrollment_required

from web.models import db, Brand, User, Course, Topic, Enrollment

main = Blueprint('main', __name__)

@main.route('/explore')
@main.route('/welcome/<int:offset>', methods=['post', 'get'])
@main.route('/welcome', methods=['post', 'get'])
def index(v=None):

    page = request.args.get('page', 1, type=int)

    match v:
        case 'latest':
            course = Course.query.order_by(Course.created.desc()).paginate(page=page, per_page=8)
        case 'oldest':
            course = Course.query.order_by(Course.created.asc()).paginate(page=page, per_page=8)
        case 'asc':
            course = Course.query.order_by(Course.title.asc()).paginate(page=page, per_page=8)
        case 'desc':
            course = Course.query.order_by(Course.title.desc()).paginate(page=page, per_page=8)
        case 'cat':
            cat = v.cat
            course = Course.query.filter(Course.cat.in_([c for c in cat]) ).all()
        case 'time':
            time = v.time
            course = Course.query.filter(Course.duration.in_([ t for t in time]) ).all()
        case 'price':
            min = v.min
            max = v.max
            course = Course.query.filter(Course.price >= min).filter(Course.price <= max) or \
                Course.query.filter(Course.price.in_(range(min, max)) ).all()
        case 'kword':
            kword = v.kword
            course = Course.query.msearch(kword, fields=['title','desc'] , limit=8)
        case 'rate':
            rate = v.rate
            course = Course.query.filter(Course.rating >= rate).all()
        case 'more':
            course = Course.query.order_by(Course.id.asc()).offset(5).all()
        case _:
            all = Course.query.all()
            course = all[0 : 16 ]
            total = len(all)
        
    brand = Brand.query.filter_by(id=2).first()

    context = { 
        'brand': brand, 
        'course': course, 
        'total' : total,
        'time' : "duration_choice" }

    return render_template("welcome/welcome.html", **context)

@main.route("/us")
def us():
    brand = Brand.query.filter_by(id=2).first()
    support_amount = "30, 40, 50, 70, 80, 90, 100, 200, 300, 400, 500"
    support_interval = "daily, weekly, monthly, quarterly, yearly"
    context = {
        "brand":brand, 
        "title" :'Us . Intellect',
        "support_amount" : support_amount, 
        "support_interval" : support_interval, 
    }
    return render_template('welcome/us.html', **context)

@main.route("/us-x")
def us_x():
    brand = Brand.query.filter_by(id=2).first()
    support_amount = "30, 40, 50, 70, 80, 90, 100, 200, 300, 400, 500"
    support_interval = "daily, weekly, monthly, quarterly, yearly"
    context = {
        "brand":brand, 
        "title" :'Us . Intellect',
        "support_amount" : support_amount, 
        "support_interval" : support_interval, 
    }
    return render_template('welcome/us_x.html', **context)

 
@main.route("/")
@login_required
#@confirm_email
def user():

    # Get the current user
    user = User.query.get(current_user.id)

    # Fetch all enrollments of the user
    enrollments = Enrollment.query.filter_by(user_id=user.id).all()

    # Prepare the response data
    response_data = []

    for enrollment in enrollments:
        # Get the course associated with the enrollment
        course = enrollment.course

        # Calculate the completion percentage for the course
        completion_percentage = course.calculate_completion_percentage(user)

        # Serialize the course data
        serialized_course = course.serialize(include_only=['title', 'image', 'slug'])

        # Add completion percentage to the serialized course data
        serialized_course['progress'] = completion_percentage
        serialized_course['percent_complete'] = completion_percentage

        # Append the serialized course to the response data
        response_data.append(serialized_course)

    # Return the response as JSON
    progress_data = response_data
    #print(progress_data)
    context = {
        'progress_data': progress_data
    }

    return render_template('index.html', **context )

#-> Preview Here
@main.route('/prev_/<string:slug>')
def prev_(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    course.views += 1
    db.session.commit()

    topiq = Topic.query.filter(Topic.course_id == course.id).first()

    #return f'{course.__dict__}'

    context = {
        'course': course,
        'topiq': topiq.title if topiq else '0-topic',
        #'data': course.__dict__  # Convert Course object to a dictionary
        'data': test_course.course_data  
    }
    #print(context['data'])
    return render_template('courses/prev.html', **context)

@main.route('/learn_/<string:slug>')
def learn_(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    _chapt = [c for c in course.lesson]
    _topiq = [ t for t in course.topic]
    context = {
        '_chapt': _chapt, '_topic':_topiq,
        'data': course,
    }

    return render_template("courses/learn3.html", **context)

@main.route("/blog")
def blog():
    return render_template('blog.html')

@main.route('/school')
@login_required
#@confirm_email
def school():
    return render_template("school.html")

#quiz
@main.route('/quiz')
@login_required
#@confirm_email
def quiz():
    return render_template("quiz/quiz.html")
    
@main.route('/qdetail', defaults={'one':'one'})
@main.route('/qdetail/<string:one>', defaults={'one':'one'})
@login_required
#@confirm_email
def qdetails(one):
    return render_template("quiz/qdetail.html")

@main.route('/qresult')
@login_required
#@confirm_email
def qresult():
    return render_template("quiz/qresult.html")

#path
@main.route('/paths')
@login_required
#@confirm_email
def path():
    return render_template("path/path.html")

@main.route('/path', defaults={'one':'one'})
@main.route('/path-of/<string:one>', defaults={'one':'one'})
@login_required
#@confirm_email
def path_of(one):
    return render_template("path/path-of.html")


#instructors
@main.route('/tutors')
@login_required
#@confirm_email
def tutor_list():
    return render_template("instructor/tutors.html", tutors = 't')

@main.route('/tutor', defaults={'t':'t'})
@main.route('/tutor/<string:t>', defaults={'t':'t'})
@login_required
#@confirm_email
def tut(t):
    return render_template("instructor/tutor.html", tutor = tutor.info )

@main.route('/play')
@login_required
#@confirm_email
def player():
    return render_template("misc/play.html")

@main.route('/materi')
@login_required
#@confirm_email
def materi():
    return render_template("misc/material.html")

@main.route('/syllabus')
@login_required
#@confirm_email
def syllabus():
    return render_template("misc/syllabus.html")

@main.route('/../json/search.json')
@main.route('/json/search.json')
def search():
    r = [
    {
        "title": "settings",
        "url": f"/{current_user.username}/update" if current_user.is_authenticated else url_for('auth.signin')
    },
    {
        "title": "dashboards > elearning",
        "url": "/"
    },
    {
        "title": "dashboards > School",
        "url": "/school"
    },
    ]
  
    c = Course.query.all() 
    return jsonify([ { 'label': c.title, 'url': url_for('main.prev', slug=str(c.slug) ) } for c in c] ) 

""" ========================================================================== """

# Actual learning interface
#-> Preview Here
@main.route('/prev/<string:slug>')
def prev(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    course.views += 1
    db.session.commit()

    return render_template('xcourse/prev.html')

@main.route('/learn/<string:slug>')
@login_required
@enrollment_required
def learn(slug):
    return render_template("xcourse/learn.html")

# Course insertion interface
@main.route('/x-insert')
def x_insert():
    return render_template("xcourse/x_insert.html")

# Course update interface
@main.route('/x-update')
def x_update():
    return render_template("xcourse/x_update.html")

# Lesson insertion interface
@main.route('/x-insert/lesson')
def x_insert_lesson():
    return render_template("xcourse/x_insert_lesson.html")

# Lesson update interface
@main.route('/x-update/lesson')
def x_update_lesson():
    return render_template("xcourse/x_update_lesson.html")

# Topic insertion interface
@main.route('/x-insert/topic')
def x_insert_topic():
    return render_template("xcourse/x_insert_topic.html")

# Topic update interface
@main.route('/x-update/topic')
def x_update_topic():
    return render_template("xcourse/x_update_topic.html")

web/templates/courses/learn2.html
{% extends 'base.html' %}
{% block title %} {{ course.title }} {% endblock title %}
{% block content %}
<main>
    <div class="container">
        <div class="row">
            <div class="col">

                <section class="scroll-section" id="title">
                    <div class="page-title-container">
                        <h1 class="mb-0 pb-0 display-4"> {{course.title}}</h1>
                        <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
                            <ul class="breadcrumb pt-0">
                                <li class="breadcrumb-item"><a href="{{url_for('main.user' if current_user.is_authenticated else 'main.index')}}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Explore</a></li>
                            </ul>
                        </nav>
                    </div>
                </section>
                                    {#    <!--------------topics-------------->
                                        {% for t in topic %}
                                        <section class="scroll-section mb-5" id="chapter2">
                                            <h2 class="small-title">{{loop.index}}. {{t.title }}</h2>
                                            <div class="card">
                                                <div class="card-body">
                                                    <div class="heading">{{t.title}}</div>
                                                    <p>{{ t.desc }}</p>
                                                </div>
                                            </div>
                                        </section>
                                        {% endfor %}
                                        <!--------------------------------------> #}
                <div>
{# <!--                     {% for c in course.lesson %}
                    <section class="scroll-section mb-5" id="chapter{{loop.index}}">
                        <h2 class="small-title">{{loop.index}}. {{c.title}}</h2>
                        <div class="card">
                            <div class="card-body">
                            {% for t in c.topiq %}
                           <div>
                            <strong> <div class="heading">{{t.title}}  </div></strong>
                                <p class="d-none">
                                    {{t.desc}}
                                    <strong>Brownie candy cookie</strong>
                                </p>
                            
                            </div>
                            {% endfor %}

                                <div class="d-flex flex-row flex-wrap">
                                   {% if course.material or course.lesson.material %}

                                    <div class="sw-30 me-2 mb-2">
                                        <div class="row g-0 rounded-sm sh-8 border">
                                            <div class="col-auto">
                                                <div class="sw-10 d-flex justify-content-center align-items-center h-100">
                                                    <i data-acorn-icon="file-text" class="text-primary" data-acorn-size="20"></i>
                                                </div>
                                            </div>
                                            <div class="col rounded-sm-end d-flex flex-column justify-content-center pe-3">
                                                <div class="d-flex justify-content-between">
                                                    <p class="mb-0 clamp-line" data-line="1"
                                                        style="overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 1;">
                                                        
                                                        {{course.material or course.lesson.material }}</p>
                                                    
                                                        <a href="{{url_for('static', filename='img/materi/'+ course.material|string or course.lesson.material|string)}}" data-bs-toggle="tooltip" data-bs-placement="top"
                                                        title="" data-delay="{'show':'1000', 'hide':'0'}"
                                                        data-bs-original-title="Download">
                                                        <i data-acorn-icon="download" class="text-alternate" data-acorn-size="17"></i>
                                                    
                                                    </a>
                                                </div>
                                                <div class="text-small text-primary">521 KB</div>
                                            </div>
                                        </div>
                                    </div>

                                    {% endif %}

                                </div>

                            </div>
                        </div>
                    </section>
                    {% endfor %} --> #}
                </div>
            </div>
            <div class="col-md-auto d-none d-lg-block" id="scrollSpyMenu">
                <ul class="nav flex-column">
                    {% for c in course.lesson %}
                    <li>
                        <a class="nav-link" href="#chapter{{loop.index}}">
                            <i data-acorn-icon="chevron-right" class="text-primary" data-acorn-size="20"></i>
                            {# <span>Lesson {{loop.index}}</span> #}
                            <span>{{c.title}}</span>
                        </a>
                    </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

web/templates/courses/learn3.html
<!DOCTYPE html>
<html lang="en" data-footer="true">
<head>
    <head>
        <title>{% block title %} Learn . Russsian Developers {% endblock title %}</title>
        {% include('incs/metas.html') %}
        {% block page_css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/plyr.css')}}">
        {% endblock page_css %}
    </head>
<body>
    <div id="root">

        {% include('incs/nav.html') %}

        <main>
            <div class="container d-flex flex-column">
                <div class="page-title-container">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <h1 class="mb-0 pb-0 display-4" id="title">{{_chapt.title}}</h1>
                            <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
                                <ul class="breadcrumb pt-0">
                                    <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Home</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-12 col-sm-6 d-flex align-items-start justify-content-end">
                            <button type="button"
                                class="btn btn-outline-primary btn-icon btn-icon-start w-100 w-sm-auto d-inline-block d-xl-none"
                                data-bs-toggle="modal" data-bs-target="#tableOfContentsModal">
                                <i data-acorn-icon="menu-right"></i>
                                <span>Contents </span>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="row d-flex flex-grow-1 overflow-hidden pb-2 h-100">
                    <div class="col-xl-8 col-xxl-9">

                        <div class="card mb-5 h-100 bg-transparent">
                        <!-------by---topics--------->
                        {% for t in _topic %}
                        {% if (t.title|slugify|lower == request.args.get('topiq')|string|slugify|lower) %}
                        <section class="scroll-section mb-5" id="topic{{loop.index}}">
                            <h4 class="small-title">{{loop.index}}. {{ t.title }}</h4>
                            <div class="card btn-next">
                                <div class="card-body">
                                    <div class="heading"><h4>{{t.title}}</h4></div>
                                    {% set tokened = t.desc|sent_tokenize %}
                                    {% for desc in tokened %}
                                    <h5 class="bit_sized_element {{'d-none' if (loop.index != 1) else '' }}">{{desc}}</h5> <br>
                                    {% endfor %}
                                </div>

                                <div class="card-footer text-center border-0 mt-3 pt-1"
                                style="margin-top: 10px;">
                                <button type="button" class="btn btn-icon btn-icon-end btn-outline-primary btn-prev">

                                    <span>Back</span>
                                    <i data-acorn-icon="chevron-left"></i>
                                </button>
                                <button type="button" class="btn btn-icon btn-icon-end btn-outline-primary btn-next">

                                    <span>Continue</span>
                                    <i data-acorn-icon="chevron-right"></i>
                                </button>
                            </div>

                            </div>
                        </section>
                        {% endif %}
                        {% endfor %}

                        </div>
                    </div>
                    <div class="d-none d-xl-flex col-xl-4 col-xxl-3 h-100 scroll-out table-of-contents-scroll" id="tableOfContentsColumn"></div>
                </div>

                <div class="modal modal-right fade" id="tableOfContentsModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Content</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body p-0">
                                <div id="tableOfContentsMoveContent" data-move-target="#tableOfContentsColumn" data-move-breakpoint="xl">
                                    <div id="courseContent">

                                        {% for c in _chapt %}

                                        <div class="card mb-2">
                                            <div class="card-body">
                                                <div class="d-flex flex-row align-content-center align-items-center cursor-pointer"
                                                    data-bs-toggle="collapse" data-bs-target="#collapse{{loop.index}}"
                                                    aria-expanded="false" aria-controls="collapse{{ loop.index }}">
                                                    <div class="sw-4 me-3">
                                                        <div class="border border-1 border-primary rounded-xl sw-4 sh-4 text-primary d-flex justify-content-center align-items-center">
                                                            {{ loop.index }}
                                                        </div>
                                                    </div>
                                                    <div> <div class="heading mb-0 {{ 'text-primary' if ( loop.index == request.args.get('page')|int ) else '' }}">
                                                        {{ c.title }}</div> </div>
                                                </div>
                                                <div id="collapse{{loop.index}}" class="accordion-collapse collapse ms-2 ps-1 {{'show' if loop.index == request.args.get('page')|int else ''}}"
                                                    data-bs-parent="#courseContent">
                                                
                                                    {% for t in c.topiq %}

                                                    <div class="row g-0 {{ 'mt-4' if (loop.index == 1) else '' }} ">
                                                        <div class="col-auto sw-1 d-flex flex-column justify-content-center align-items-center position-relative me-4">
                                                            <div class="w-100 d-flex sh-1"></div>
                                                            <div class="rounded-xl shadow d-flex flex-shrink-0 justify-content-center align-items-center">
                                                                <div class="bg-primary sw-1 sh-1 rounded-xl position-relative"></div>
                                                            </div>
                                                            <div class="w-100 d-flex h-100 justify-content-center position-relative">
                                                                <div class="line-w-1 bg-separator h-100 position-absolute"></div>
                                                            </div>
                                                        </div>
                                                        <div class="col mb-2">
                                                            <div class="h-100">
                                                                <div class="d-flex flex-column justify-content-start">
                                                                    <div class="d-flex flex-column">
                                                                         <a href="?topiq={{t.title|slugify|lower}}"  
                                                                        class="heading {{'muted-link' if (loop.index != 1) else 'muted-link' }} ">
                                                                        {{ loop.index|string + '. ' + t.title }}</a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    {% endfor %}
                                                    
                                                </div>
                                            </div>
                                        </div>

                                    {% endfor %}

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

        {% include('incs/footer.html') %}

    </div>

    {% include('incs/search.html') %}

    <script src="{{url_for('static', filename='js/vendor/jquery-3.5.1.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/OverlayScrollbars.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/autoComplete.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/clamp.min.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons-interface.js')}}"></script>
    <script src="{{url_for('static', filename='icon/acorn-icons-learning.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/plyr.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/movecontent.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/helpers.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/globals.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/nav.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/search.js')}}"></script>
    <script src="{{url_for('static', filename='js/base/settings.js')}}"></script>
    <script src="{{url_for('static', filename='js/pages/misc.player.js')}}"></script>
    <script src="{{url_for('static', filename='js/common.js')}}"></script>
    <script src="{{url_for('static', filename='js/scripts.js')}}"></script>

    {% block page_js %}
    <script src="{{ url_for('static', filename='js/pages/learn.bit.js')}}"></script>
 <!--    <script src="{{ url_for('static', filename='js/pages/plyr.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/vendor/misc.player.js')}}"></script> -->
    {% endblock page_js %}

</body>
</html>